### PR TITLE
Ignore query string for callback url

### PR DESCRIPTION
**Pull request by carsonreinke**
I was recently burned by this pretty bad.  Updating to omniauth-oauth2 1.4.0, the callback url has now included the query string.  BigCommerce services appears to also validate on this.

Some related information about this:
https://github.com/intridea/omniauth-oauth2/pull/82
https://github.com/intridea/omniauth-oauth2/pull/70

### CODE REVIEW

**Comment by carsonreinke** [comment]
@philipmuir Any change you can possibly address immediately?  This should render this gem unusable until deployed.

**Comment by mattolson** [comment]
@carsonreinke This is indeed a bug introduced by omniauth-oauth2. Thanks for submitting the fix. Please rebase on master and we'll merge it right away. Rebasing should fix the Travis failure as well.

**Comment by carsonreinke** [comment]
Green, but oddly have .gitignore in there from my change.  Let me know if you want me to mess around.

**Comment by mattolson** [comment]
👍

**Comment by mattolson** [comment]
Thanks for the contribution. I have one more change I want to add, and then we'll cut a new release.

**Pull request merged**
